apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: node3
  name: node3
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mysql/mysql-server:8.0
    generation: null
    importPolicy: {}
    name: "8.0"
status:
  dockerImageRepository: ""
